// ═══════════════════════════════════════════════════════════
//  PREVIFUEGO — clientes.js  v1.0
//  Base de datos de 341 clientes
//  Generado automáticamente desde PREVIFUEGO_BASE_DE_DATOS_v2
// ═══════════════════════════════════════════════════════════

var PF_CLIENTES = [
  {
    "codigo": "K002",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K002 - 9 DE OCTUBRE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K003",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K003 - PLAZA QUIL",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K007",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K007 - ALBORADA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K012",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K012 - RIO CENTRO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K021",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K021 - MALL EL SOL",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K025",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K025 - MOBIL DURAN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K029",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K029 - MALECON 2000",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K034",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K034 - VIA DAULE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K037",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K037 - DOMINGO COMIN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K039",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K039 - AEROPUERTO GY",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K045",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K045 - BOYACA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K048",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K048 - PENINSULA SALINAS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K051",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K051 - SAN MARINO PLANTA ALTA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K052",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K052 - LAS PEÃ????AS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K053",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K053 - PASEO SHOPPING BABAHOYO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K055",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K055 - MOBIL CORDOVA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K058",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K058 - MALL DEL SUR PLANTA ALTA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K059",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K059 - MALL DEL SUR P/B",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K063",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K063 - RIO CENTRO SUR",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K065",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K065 - MILAGRO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K067",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K067 - MOBIL BENEFICENCIA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K069",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K069 - LOJA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARJORIE MONTAÑO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K074",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K074 - CALIFORNIA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K075",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K075 - MOBIL KENNEDY",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K076",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K076 - PARQUE CENTENARIO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K077",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K077 - RIO CENTRO LOS CEIBOS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K078",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K078 - SHOPPING DAULE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K079",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K079 - BABAHOYO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K082",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K082 - SHOPPING PLAYAS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "WILLIAM ZAMBRANO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K083",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K083 - MUCHO LOTE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K085",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K085 - MOBIL CEIBOS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K087",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K087 - TERMINAL TERRESTRE GYQ",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K088",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K088 - HIPERMARKET VIA DAULE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K090",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K090 - MACHALA CENTRO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K091",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K091 - MACHALA RIO CENTRO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K092",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K092 - EL FORTIN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K093",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K093 - QUEVEDO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K094",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K094 - OUTLET DURAN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K095",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K095 - PASEO SHOP KM 9 VIA DAULE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K096",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K096 - PORTETE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K105",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K105 - HIPER MARKET",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K106",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K106 - SHOPPING QUEVEDO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K109",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K109 - CITY MALL PA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K110",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K110 - CITY MALL PB",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K115",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K115 - ENTRADA DE LA 8",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K117",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K117 - 29 Y SEDALANA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K123",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K123 - RIOCENTRO EL DORADO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K124",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K124 - GRAN AKI",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARJORIE MONTAÑO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K129",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K129 - LLEVAR 5 ESQUINAS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JOHANNA ESPIN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K142",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K142 - SUPER AKI VINCES",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K145",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K145 - SUPER AKI SAN EDUARDO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LEONARDO MONCAYO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K148",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K148 - TERMINAL TERRESTRE MACHALA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K149",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K149 - PETROCOMERIAL VENTANAS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K153",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K153 - LIGA CANTONAL DURAN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K154",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K154 - PASCUALES",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K161",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K161 - MALL DEL RIO GYE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K162",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K162 - DAULE ESTACION",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K165",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K165 - PLAZA TIA DURAN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUDITH CASTRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K169",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K169 - PLAZA PACIFICO DAULE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K171",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K171 - SHELL ABU DABI",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K172",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K172 - MALL DEL NORTE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K173",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K173 - OASIS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "MARIUXI CHICO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K175",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K175 - VIA A LA COSTA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K176",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K176 - SUPERCINES",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "LAURA SANTILLAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K178",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K178 - MALECON SALINAS",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K179",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K179 - ESTACION SANTA ELENA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "JUAN CARLOS LOPEZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K180",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K180 - GRAN PIAZZA MACHALA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K182",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K182 - JUAN TANCA MARENGO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "NURIA FARRO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K183",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K183 - LA QUADRA QUEVEDO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K184",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K184 - SUPERMAXI MACHALA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K186",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K186 - PINTULAC MILAGRO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "K187",
    "grupo": "Grupo KFC",
    "marca": "KFC",
    "nombre": "K187 - DOMINGO COMIN Y ERNESTO ALBAN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G042",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G042 - QUITO AQUIRRE CERRADO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G044",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G044 - BOYACA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G045",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G045 - TUNGURAHUA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G047",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G047 - ALBORADA",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G048",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G048 - TERMINAL TERRESTRE",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G049",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G049 - OUTLET DURAN",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G050",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G050 - MALL DEL SUR",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G051",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G051 - SHOPPING QUEVEDO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G052",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G052 - CITY MALL",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "G054",
    "grupo": "Grupo KFC",
    "marca": "GUS",
    "nombre": "G054 - RIOCENTRO EL DORADO",
    "razon": "INT FOOD SERVICES CORP S.A.",
    "ruc": "1791415132001",
    "responsable": "RUSBELIS FARIAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J001",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J001 - MALL DEL SOL",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J002",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J002 - SAN MARINO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J005",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J005 - CAJUN CEIBOS",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J006",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J006 - CAJUN PUNTILLA",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "MARIA MORAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J008",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J008 - TERMINAL",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J010",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J010 - RIO CENTRO NORTE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J011",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J011 - CITY MALL",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J019",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J019 - RIOCENTRO EL DORADO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "MARIA MORAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J020",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J020 - CAJUN PENINSULA",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "XAVIER MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J021",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J021 - MALL DEL SUR",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "MARIA MORAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J029",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J029 - CAJUN MALL DEL NORTE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "MARIA MORAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J030",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J030 - RIO CENTRO SUR GYE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "MARIA MORAN",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "J031",
    "grupo": "Grupo KFC",
    "marca": "CAJUN",
    "nombre": "J031 - GRAN PIAZZA MACHA",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M010",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M010 - MALECON",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ALEX ANDRADE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M011",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M011 - MALL SUR",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ALEX ANDRADE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M014",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M014 - RIOCENTRO SUR",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "JORGE PUNGUIL",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M021",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M021 - TERMINAL TER GYQ.",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M028",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M028 - VILLAGE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M031",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M031 - RIO CENTRO NORTE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M032",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M032 - SHOPPING QUEVEDO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M033",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M033 - CITY MALL",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M035",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M035 - GARZOTA",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "JORGE PUNGUIL",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M037",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M037 - 9 DE OCTUBRE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "JORGE PUNGUIL",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M039",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M039 - PASEO SHOPPING BABAHOYO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "OMAR ROSAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M043",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M043 - EL FORTIN",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "JORGE PUNGUIL",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M046",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M046 - SAN MARINO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "JORGE PUNGUIL",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M047",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M047 - PASEO SHOPPING DURAN",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ALEX ANDRADE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M050",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M050 - RIOCENTRO EL DORADO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ALEX ANDRADE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M056",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M056 - AEROPUERTO GYE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M057",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M057 - ALBORADA",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ALEX ANDRADE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M058",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M058 - LAS PENAS",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "JORGE PUNGUIL",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M061",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M061 - PORTETE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M062",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M062 - MN MALL DEL NORTE GY",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "LUIS LOMAS",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "M065",
    "grupo": "Grupo KFC",
    "marca": "MENESTRAS DEL NEGRO",
    "nombre": "M065 - GRAN PIAZZA MACH",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "R003",
    "grupo": "Grupo KFC",
    "marca": "CASA RES",
    "nombre": "R003 - 9 DE OCTUBRE",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ISABEL GARCIA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "R004",
    "grupo": "Grupo KFC",
    "marca": "CASA RES",
    "nombre": "R004 - SAN MARINO",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ISABEL GARCIA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "R008",
    "grupo": "Grupo KFC",
    "marca": "CASA RES",
    "nombre": "R008 - MALL DEL SOL",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ISABEL GARCIA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "R010",
    "grupo": "Grupo KFC",
    "marca": "CASA RES",
    "nombre": "R010 - FRANCISCO DE ORELLANA",
    "razon": "SHEMLON S.A.",
    "ruc": "1792049504001",
    "responsable": "ISABEL GARCIA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A006",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A006 - TERMINAL GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A007",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A007 - SAN MARINO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A019",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A019 - MALL DEL SOL PATIO COMIDAS",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A020",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A020 - VILLAGE PLAZA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A024",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A024 - MALL DEL SUR",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A033",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A033 - CITY MALL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A037",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A037 - RIOCENTRO EL DORADO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "A047",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "A047 - RIO CENTRO NORTE GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "POLLETT ZEA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "B001",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "B001 - STATION SPORTS BAR",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "JOFFRE PEREZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "F003",
    "grupo": "Grupo KFC",
    "marca": "AMERICAN DELI",
    "nombre": "F003 - DOLCE INCONTRO AERGYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "JOFFRE PEREZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS04",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS04 - MALL DEL SOL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS09",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS09 - RIO CENTRO SUR",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS16",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS16 - PUNTILLA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS20",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS20 - RIO CENTRO NORTE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS22",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS22 - POLICENTRO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS37",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS37 - DORADO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "BS38",
    "grupo": "Grupo KFC",
    "marca": "BASKIN",
    "nombre": "BS38 - CEIBOS BASKIN",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN04",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN04 - MALL DEL SOL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN16",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN16 - PUNTILLA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN26",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN26 - PREEMB INTER GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN31",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN31 - RIOCENTRO CEIBOS",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN34",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN34 - RIO CENTRO SUR CINNABON TO GO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN35",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN35 - RIO CENTRO NORTE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CN37",
    "grupo": "Grupo KFC",
    "marca": "CINNABON",
    "nombre": "CN37 - EL DORADO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "NESTOR PINARGOTE",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I002",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I002 - RIOCENTRO CEIBOS",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I003",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I003 - MALL DEL SOL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I004",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I004 - MALL DEL SUR",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I005",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I005 - SAN MARINO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I012",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I012 - TERMINAL TERRESTRE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I017",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I017 - RIO CENTRO NORTE GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "I018",
    "grupo": "Grupo KFC",
    "marca": "ILCAPPO",
    "nombre": "I018 - DORADO GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "INES BRIONES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E006",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E006 - MALL EL SOL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "AMANDA FUENTES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E007",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E007 - URDESA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "AMANDA FUENTES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E009",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E009 - CEIBOS",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "ERICKA DELGADO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E010",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E010 - SAN MARINO PB",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "AMANDA FUENTES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E022",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E022 - ISLA EXP GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "ERICKA DELGADO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E023",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E023 - PREEMB NAC GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "ERICKA DELGADO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E026",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E026 - PUNTILLA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "ERICKA DELGADO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E030",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E030 - CITY MALL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "AMANDA FUENTES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E031",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E031 - POLICENTRO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "AMANDA FUENTES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "E044",
    "grupo": "Grupo KFC",
    "marca": "ESPAÑOL",
    "nombre": "E044- EL DORADO",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "ERICKA DELGADO",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "DI01",
    "grupo": "Grupo KFC",
    "marca": "DOLCE",
    "nombre": "DI01 - DOLCE INCONTRO MALL DEL SOL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FREDDY VERA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "DI02",
    "grupo": "Grupo KFC",
    "marca": "DOLCE",
    "nombre": "DI02 - DOLCE INCONTRO CEIBOS",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FREDDY VERA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "DI03",
    "grupo": "Grupo KFC",
    "marca": "DOLCE",
    "nombre": "DI03 - DOLCE INCONTRO SAMBORONDON",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FREDDY VERA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "DI04",
    "grupo": "Grupo KFC",
    "marca": "DOLCE",
    "nombre": "DI04 - DOLCE INCONTRO URDESA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FREDDY VERA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CA01",
    "grupo": "Grupo KFC",
    "marca": "CAFA",
    "nombre": "CA01 - CAFE ASTORIA SALIDA INTERNACIONAL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FELIX ESPINOZA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CA02",
    "grupo": "Grupo KFC",
    "marca": "CAFA",
    "nombre": "CA02 - CAFE ASTORIA PREEMBARQUE INTERNACIONAL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FELIX ESPINOZA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "CA03",
    "grupo": "Grupo KFC",
    "marca": "CAFA",
    "nombre": "CA03 - CAFE DUPORT HALL PRINCIPAL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FELIX ESPINOZA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "T032",
    "grupo": "Grupo KFC",
    "marca": "TROPIBURGER",
    "nombre": "T032 - TERMINAL",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FRANCISCO VELOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "T043",
    "grupo": "Grupo KFC",
    "marca": "TROPIBURGER",
    "nombre": "T043 - MALL EL FORTIN",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FRANCISCO VELOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "T051",
    "grupo": "Grupo KFC",
    "marca": "TROPIBURGER",
    "nombre": "T051 - MALECON GYE",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "FRANCISCO VELOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "T054",
    "grupo": "Grupo KFC",
    "marca": "TROPIBURGER",
    "nombre": "T054 - GRAN PIAZZA MACHALA",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "DARIO COCHANCELA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "H068",
    "grupo": "Grupo KFC",
    "marca": "HELADERIAS",
    "nombre": "H068 - MALL DEL NORTE PATIO DE COMIDAS",
    "razon": "DELI INTERNACIONAL S.A.",
    "ruc": "1792072018001",
    "responsable": "MIREYA MESA",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V003",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V003 - SAN MARINO",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V004",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V004 - AEROPUERTO",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V005",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V005 - URDESA",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V015",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V015 - CEIBOS",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V016",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V016 - POLICENTRO",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V021",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V021 - MALL DEL SOL",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V024",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V024 - PREEMBARQUE NACIONAL",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V048",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V048 - MALL DEL RIO GYE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V053",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V053 - PUERTO SANTA ANA",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V055",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V055 - MALL DEL SOL ZONA GASTRO",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V057",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V057 - CORAL SAMBORONDON",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V066",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V066 PLAZA PACIFICO DAULE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V069",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V069 QUEVEDO PASEO SHOPPING",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "GLORIA MUÑOZ",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V073",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V073 - CORAL LOS CEIBOS",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V075",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V075 - PASEO SHOPPING MACHALA",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V076",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V076 - TERMINAL TERRESTE GYE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V077",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V077 - FERRISARIATO KENNEDY",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V078",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V078 - RIOCENTRO SUR GYE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V079",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V079 - MILAGRO",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V080",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V080 - AGORA GYE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V082",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V082 - GRAN PIAZZA MACHA",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V084",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V084 - TORRE MILLENIUM",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V085",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V085 - PASEO SHOPPING PENINSULA",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V086",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V086 - PASEO SHOPPING PLAYAS",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "PAOLA MIELES",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V087",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V087 - PASEO SHOPPING DAULE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V089",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V089 - PINTULAC MILAGRO",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "V090",
    "grupo": "Grupo KFC",
    "marca": "JUAN VALDEZ",
    "nombre": "V090 - SUPER AKI LA JOYA GYE",
    "razon": "PROMOTORA ECUATORIANA DE CAF DE COLOMBIA S.A.",
    "ruc": "1792141486001",
    "responsable": "",
    "mes": "",
    "freqMant": "1 año",
    "freqRec": "3 años"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "TORO ASADO PLANTA",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA CENTENARIO",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA CRISTO",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA ENTRE RIOS",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA ESTEROS",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA SAMANES",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOCENTRO",
    "nombre": "NOVOCENTRO DURAN",
    "razon": "NOVOPAN DEL ECUADOR S.A.",
    "ruc": "1790374343001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "PJ BUENA VISTA",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO CORAL CEIBOS",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSUCORP DURAN",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MUNDICABLES",
    "nombre": "MUNDICABLES",
    "razon": "MUNDICABLES S.A.",
    "ruc": "0992923172001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "INDUTORRES",
    "nombre": "INDUTORRES",
    "razon": "INDUTORRES S.A.",
    "ruc": "0990881561001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SECOMATICO",
    "nombre": "SECOMATICO",
    "razon": "LAVANDERIA SECOMATICO SA",
    "ruc": "0990058229001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "BONTEX",
    "nombre": "BONTEX",
    "razon": "BONTEX S.A.",
    "ruc": "0992273429001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KURMA",
    "nombre": "KURMA",
    "razon": "INMOBILIARIA KURMA S.A.",
    "ruc": "0990872988001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KHOURY",
    "nombre": "INMOBILIARIA KHOURY",
    "razon": "INMOBILIARIA KHOURY CIA. LTDA.",
    "ruc": "0990062900001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "FUJIFILM",
    "nombre": "FUJIFILM",
    "razon": "MONTENEGRO SALAS VICTOR MANUEL",
    "ruc": "0925739997001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOEVENTOS",
    "nombre": "COLEGIO SAN LUIS REY DE FRANCIA",
    "razon": "PRODUCCIONES Y EVENTOS NOVOEVENTOS S.A.",
    "ruc": "1792025435001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "ING. CHANE",
    "nombre": "ING CHANE",
    "razon": "ING. MARCO ANTONIO CHANE LEON",
    "ruc": "0903180503001",
    "responsable": "",
    "mes": "ENERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA PLAZA TIA CENTRAL",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "PAPIZZEC MILAGRO",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "PJ GARZOTA",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "EMPANADAS PACO CITY MALL",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "EMPANADAS PACO VERMONT PLAZA",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO RIOC CEIBOS",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "CEBICHES RIOC CEIBOS",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "IVAN RIVADENEIRA CEBICHES EL DORADO",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE PLANTA",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOE",
    "nombre": "NOE BOCCA SAMBO",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOE",
    "nombre": "NOE MALL DEL SOL",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "FEDERAL",
    "nombre": "FEDERAL",
    "razon": "IMPORTADORA FEDERAL S.A.",
    "ruc": "0990011451001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "ROLORTIZ",
    "nombre": "ROLORTIZ",
    "razon": "IMPORTADORA ROLORTIZ CIA. LTDA.",
    "ruc": "0190157075001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "GASEC",
    "nombre": "GASEC",
    "razon": "GASEC S.A.",
    "ruc": "0992143576001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SOCELEC",
    "nombre": "SOCELEC",
    "razon": "SOCIEDAD ELECTRONICA S.A. SOCELEC",
    "ruc": "0190370585001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "FIGURA Y SALUD / YOPIURA",
    "nombre": "FIGURA Y SALUD",
    "razon": "BERREZUETA RIOS FERNANDO JAVIER",
    "ruc": "0917103939001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "FIGURA Y SALUD / YOPIURA",
    "nombre": "YOPIURA ENTRE RIOS",
    "razon": "BERREZUETA RIOS FERNANDO JAVIER",
    "ruc": "0917103939001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PHARMEDICAL",
    "nombre": "PHARMEDICAL PARQUE COLON",
    "razon": "GIL POVEDA NADIA VIVIANA",
    "ruc": "0922856802",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "ALMODOBAR",
    "nombre": "ALMODOBAR GUAYARTE",
    "razon": "ALMODOBAR",
    "ruc": "0993142905001",
    "responsable": "",
    "mes": "FEBRERO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "TORO ASADO DURAN",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "TORO RIOC EL DORADO",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA PLAZA TIA LA JOYA",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "PAPA JOHNS VILLA CLUB",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PLAZA TIA EL CAMINO PACO",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PLAZA TIA LA JOYA PACO",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE SUPERCINES ORELLANA",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CONGAS",
    "nombre": "CONGAS PORTOVIEJO",
    "razon": "COMPANIA NACIONAL DE GAS CONGAS C.A.",
    "ruc": "1790273482001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PROBANEN",
    "nombre": "PROBANEN",
    "razon": "PROBANEN S.A.S.",
    "ruc": "0993388441001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MARCELO FREIRE",
    "nombre": "FREIRE VILLA CLUB",
    "razon": "MARCELO FREIRE S.A.",
    "ruc": "0990638861001",
    "responsable": "",
    "mes": "MARZO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "TORO PICHINCHA Y LUQUE",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOCENTRO",
    "nombre": "NOVOCENTRO JUAN MONTALVO",
    "razon": "NOVOPAN DEL ECUADOR S.A.",
    "ruc": "1790374343001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOCENTRO",
    "nombre": "NOVOCENTRO LAS AGUAS",
    "razon": "NOVOPAN DEL ECUADOR S.A.",
    "ruc": "1790374343001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "PAPA JOHNS SAMBO CORAL",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO 9 DE OCT Y G AVILES",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO COMISARIATO VIA A LA C",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MALL DEL RIO",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO PLAZA TIA SALITRE",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO TERMINAL",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "CEBICHES BUENA VISTA SOCIEDAD DE HECHO",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "CEBICHES CITY MALL",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "CEBICHES DE LA RUMIÑAHUI URDESA",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "CEBICHES RIOCENTRO PUNTILLA",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "CEBICHES",
    "nombre": "CEBICHES SAN MARINO",
    "razon": "CITYMAR",
    "ruc": "1792870259001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSU DORADO",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSUCORP CITY MALL",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSUCORP MALL DEL SUR",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "IKURA",
    "nombre": "IKURA",
    "razon": "IKURA ASIAN FOOD S.A.S.",
    "ruc": "0993381020001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "AGO SAS",
    "nombre": "AGO SAS",
    "razon": "AGO S.A.S.",
    "ruc": "0993332208001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MARCELO FREIRE",
    "nombre": "FREIRE ALLYSON ALBORADA",
    "razon": "MARCELO FREIRE S.A.",
    "ruc": "0990638861001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "LITTLE ITALY",
    "nombre": "LITTLE ITALY MALL DEL SOL",
    "razon": "LITTLEITALY ECUADOR CIA. LTDA.",
    "ruc": "0993033081001",
    "responsable": "",
    "mes": "ABRIL",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "TORO ASADO CHIMBORAZO",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA DURAN CENTRO",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA MUCHO LOTE",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA PASCUALES",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA PORTETE 17",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA PORTETE 38",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA SUBURBIO",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOCENTRO",
    "nombre": "NOVOCENTRO ORELLANA",
    "razon": "NOVOPAN DEL ECUADOR S.A.",
    "ruc": "1790374343001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO RIOCENTRO SUR",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOREA MOTORS",
    "nombre": "KOREA MOTORS",
    "razon": "KOREA MOTORS LHG IMPORT S.A.",
    "ruc": "0993004391001",
    "responsable": "",
    "mes": "MAYO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "BABAHOYO TORO ASADO",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "TORO ASADO DORADO",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA CHIMBORAZO Y VELEZ",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA ENTRADA DE LA 8",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA GUASMO",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA MILAGRO",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA SAN FELIPE",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA SAUCES",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "ALBORADA PAPIZZEC",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "MALL DEL SUR PAPIZZEC",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "RIOCENTRO DORADO PAPIZZEC",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "URDESA PAPIZZEC",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MALL EL FORTIN ISLA",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MALL FORTIN",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO PLANTA DURAN",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO TIA BASTION",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSU MALL DEL SUR",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "JUNIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA DURAN",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JULIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA MUCHO LOTE 1",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "JULIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO 9 OCT Y G AVILES",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JULIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MALL DEL SUR",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JULIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO PLAZA TIA DURAN",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JULIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO VILLAGE",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "JULIO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "RIOC CEIBOS PAPIZZEC",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MALL DEL NORTE",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO SHOPPING VIA A DAULE",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE MALL DEL NORTE",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE MALL DEL SOL",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE PLAZA BATAN",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSU MALL DEL NORTE",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PROCORPORATION",
    "nombre": "PROCORPORATION",
    "razon": "PROCORPORATION S.A.",
    "ruc": "0992361751001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PRODUCSOL",
    "nombre": "PRODUCSOL",
    "razon": "PRODUCSOL S.A.",
    "ruc": "0992701692001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MARCELO FREIRE",
    "nombre": "FREIRE PEÑAFIEL MARJORIE",
    "razon": "MARCELO FREIRE S.A.",
    "ruc": "0990638861001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MARCELO FREIRE",
    "nombre": "MARCELO FREIRE PEÑAFIEL",
    "razon": "MARCELO FREIRE S.A.",
    "ruc": "0990638861001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MARCELO FREIRE",
    "nombre": "MARCELO FREIRE S.A.",
    "razon": "MARCELO FREIRE S.A.",
    "ruc": "0990638861001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "ING. CHANE",
    "nombre": "CHANE",
    "razon": "ING. MARCO ANTONIO CHANE LEON",
    "ruc": "0903180503001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "MARYAH SPA",
    "nombre": "MARYAH SPA CC LAS VITRINAS",
    "razon": "MARYAH SPA S.A.S.",
    "ruc": "0993383841001",
    "responsable": "",
    "mes": "AGOSTO",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO UNIV ESTATAL",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "SEPTIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "FIDEO NAPOLITANO",
    "nombre": "FIDEO NAPOLITANO",
    "razon": "INDUSTRIA DE FIDEO NAPOLITANO S.A. INFINASA",
    "ruc": "0992234024001",
    "responsable": "",
    "mes": "SEPTIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORRES DEL SOL",
    "nombre": "TORRES DEL SOL",
    "razon": "EDIFICIO TORRES DEL SOL 1",
    "ruc": "0992494867001",
    "responsable": "",
    "mes": "SEPTIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "EMPANADAS PACO MALECON",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "OCTUBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "EMPANADAS PACO MALL DEL SOL",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "OCTUBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MUCHO LOTE COMISARIATO",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "OCTUBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "SHIATSUCORP",
    "nombre": "SHIATSU MALL DEL SOL",
    "razon": "SHIATSUCORP S.A.S.",
    "ruc": "1793207908001",
    "responsable": "",
    "mes": "OCTUBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "JOYERIA MARTITHA",
    "nombre": "JOYERIA MARTITHA CENTRO",
    "razon": "MARTHA CECILIA CASTILLO VALDEZ",
    "ruc": "0903482545001",
    "responsable": "",
    "mes": "OCTUBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "JOYERIA MARTITHA",
    "nombre": "JOYERIA MARTITHA MALL DEL SOL",
    "razon": "MARTHA CECILIA CASTILLO VALDEZ",
    "ruc": "0903482545001",
    "responsable": "",
    "mes": "OCTUBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA VILLA CLUB",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PAPA JOHNS",
    "nombre": "CIUDAD DEL SOL PAPIZZEC",
    "razon": "PAPIZZEC S.A.",
    "ruc": "1791957342001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "KOBE PLAZA TIA JOYA",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO MALECON Y COLON",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EMPANADAS PACO",
    "nombre": "PACO TIA VIA A LA COSTA",
    "razon": "EMPACALLE S.A.",
    "ruc": "0993053910001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE BAMBOO PLAZA VIA A LA C",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE URDESA",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOE",
    "nombre": "NOE SAN MARINO",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "EQUILIBRIUM",
    "nombre": "EQUILIBRIUM",
    "razon": "EDIFICIO EQUILIBRIUM CENTRO DE ARMONIA",
    "ruc": "0992497815001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "PELUQUERIA YENS",
    "nombre": "PELUQUERIA YENS",
    "razon": "CEVALLOS ABARCA YEN ESPERANZA",
    "ruc": "1702933944001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOEVENTOS",
    "nombre": "CJNC31  PIAZZA MACHALA",
    "razon": "PRODUCCIONES Y EVENTOS NOVOEVENTOS S.A.",
    "ruc": "1792025435001",
    "responsable": "",
    "mes": "NOVIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORO ASADO",
    "nombre": "EL TORO ASADO FORTIN",
    "razon": "BAZFEX S.A.",
    "ruc": "1792510457001",
    "responsable": "",
    "mes": "DICIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "TORTAMANIA",
    "nombre": "TORTAMANIA URDESA",
    "razon": "TORTAMANIA S.A.S",
    "ruc": "0993366752001",
    "responsable": "",
    "mes": "DICIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "NOVOCENTRO",
    "nombre": "NOVOCENTRO SAMBORONDON",
    "razon": "NOVOPAN DEL ECUADOR S.A.",
    "ruc": "1790374343001",
    "responsable": "",
    "mes": "DICIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE RIOC CEIBOS",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "DICIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  },
  {
    "codigo": "",
    "grupo": "Independiente",
    "marca": "KOBE",
    "nombre": "KOBE RIOC ENTRE RIOS",
    "razon": "SUSHICORP S.A.S.",
    "ruc": "1792256267001",
    "responsable": "",
    "mes": "DICIEMBRE",
    "freqMant": "1 año",
    "freqRec": "1 año"
  }
];

// ── BUSCAR CLIENTE POR NOMBRE ─────────────────────────────────
function pfBuscarCliente(nombreLocal) {
  if (!nombreLocal) return null;
  var n = nombreLocal.toLowerCase().replace(/[^a-z0-9 ]/g, "");
  // Búsqueda exacta primero
  for (var i = 0; i < PF_CLIENTES.length; i++) {
    var c = PF_CLIENTES[i];
    var cn = (c.nombre || "").toLowerCase().replace(/[^a-z0-9 ]/g, "");
    if (cn === n) return c;
  }
  // Búsqueda parcial — el nombre del local contiene el del cliente o viceversa
  var mejorMatch = null, mejorScore = 0;
  for (var i = 0; i < PF_CLIENTES.length; i++) {
    var c = PF_CLIENTES[i];
    var cn = (c.nombre || "").toLowerCase().replace(/[^a-z0-9 ]/g, "");
    var marca = (c.marca || "").toLowerCase();
    // Verificar si el código está en el nombre
    if (c.codigo && nombreLocal.toUpperCase().indexOf(c.codigo) !== -1) return c;
    // Score por palabras en común
    var palabras = n.split(" ").filter(function(w) { return w.length > 2; });
    var score = 0;
    for (var j = 0; j < palabras.length; j++) {
      if (cn.indexOf(palabras[j]) !== -1) score++;
      if (marca.indexOf(palabras[j]) !== -1) score += 0.5;
    }
    if (score > mejorScore) { mejorScore = score; mejorMatch = c; }
  }
  return mejorScore >= 1 ? mejorMatch : null;
}

// ── CLIENTES DE JUNIO ─────────────────────────────────────────
var PF_CLIENTES_JUNIO = PF_CLIENTES.filter(function(c) {
  return c.mes && c.mes.toUpperCase().indexOf("JUN") !== -1;
});

// Cajun también es junio (código J)
PF_CLIENTES.forEach(function(c) {
  if (c.codigo && c.codigo.charAt(0) === "J" && c.grupo === "Grupo KFC") {
    if (!PF_CLIENTES_JUNIO.find(function(x) { return x.codigo === c.codigo; })) {
      PF_CLIENTES_JUNIO.push(c);
    }
  }
});

console.log("PF_CLIENTES cargados:", PF_CLIENTES.length, "| Junio:", PF_CLIENTES_JUNIO.length);
